-- Migration: create_test_table
create table if not exists test_table (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now()
);
